# example netlify.toml
[build]
  base = "backend"
  command = "pnpm build"
  functions = "netlify/functions"
  publish = "dist"
  ## more info on configuring this file: https://ntl.fyi/file-based-build-config

